import { OrionSatelliteFeatureType } from '../../../models/geo-fencing.models';

export const FACILITY_TYPE_MAP: Record<string, OrionSatelliteFeatureType> = {
  airport: 'airport', aerodrome: 'airport', airfield: 'airport', heliport: 'airport',
  port: 'port', ports: 'port', harbour: 'port', harbours: 'port', harbor: 'port', harbors: 'port',
  seaport: 'port', sea_port: 'port', dock: 'port', docks: 'port', marina: 'port', pier: 'port',
  quay: 'port', jetty: 'port', wharf: 'port', shipyard: 'port', boatyard: 'port', crane: 'port',
  crane_rail: 'port', ferry: 'port', ferry_terminal: 'port', harbour_master: 'port', port_terminal: 'port',
  container_terminal: 'port', cargo_terminal: 'port', breakwater: 'port', dolphin: 'port', mooring: 'port',
  anchorage: 'port', berth: 'port',
  warehouse: 'warehouse', depot: 'warehouse', storage_depot: 'warehouse',
  industrial: 'industrial', industry: 'industrial', factory: 'industrial',
  military: 'military', barracks: 'military', military_base: 'military',
  hydro: 'hydro', hydroelectric: 'hydro', hydropower: 'hydro',
  solar: 'solar', photovoltaic: 'solar', pv: 'solar',
  wind: 'wind', wind_turbine: 'wind', windfarm: 'wind',
  gas: 'gas', natural_gas: 'gas', lng: 'gas', cng: 'gas',
  coal: 'coal', lignite: 'coal',
  oil: 'oil', diesel: 'oil', petroleum: 'oil', fuel_oil: 'oil',
  nuclear: 'nuclear', atomic: 'nuclear',
  geothermal: 'geothermal', geotherm: 'geothermal',
  biomass: 'biomass', biogas: 'biomass', wood: 'biomass', bagasse: 'biomass',
  waste: 'waste', waste_to_energy: 'waste', landfill_gas: 'waste',
  storage: 'storage', battery: 'storage', pumped_hydro: 'storage',
  cogeneration: 'cogeneration', chp: 'cogeneration', combined_heat_power: 'cogeneration',
  petcoke: 'petcoke',
  'wave and tidal': 'wave_and_tidal', wave_and_tidal: 'wave_and_tidal', wave: 'wave_and_tidal',
  tidal: 'wave_and_tidal', tidal_stream: 'wave_and_tidal',
  other: 'other'
};

export const FACILITY_TYPE_DOT_CLASSES: Record<string, string> = {
  hydro: 'bg-[#2563eb]',
  solar: 'bg-[#facc15]',
  wind: 'bg-[#16a34a]',
  gas: 'bg-[#f59e0b]',
  coal: 'bg-[#111827]',
  oil: 'bg-[#f97316]',
  nuclear: 'bg-[#dc2626]',
  geothermal: 'bg-[#ec4899]',
  biomass: 'bg-[#84cc16]',
  waste: 'bg-[#8b5cf6]',
  storage: 'bg-[#06b6d4]',
  cogeneration: 'bg-[#14b8a6]',
  petcoke: 'bg-[#78716c]',
  wave_and_tidal: 'bg-[#0ea5e9]',
  airport: 'bg-[#9333ea]',
  port: 'bg-[#0d9488]',
  warehouse: 'bg-[#92400e]',
  industrial: 'bg-[#6b7280]',
  military: 'bg-[#d71c1c]',
  other: 'bg-[#a3a3a3]',
};
