exclude_paths:
  - "**/*.html"
  - "**/*.css"
  - "**/*.scss"
  - "**/*.md"
  - "**/*.sh"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.map"
  - ".nyc_output/**"
  - "coverage/**"
  - "backend/static/**"
  - "backend/migrations/**"
  - "backend/orion/services/elastic_manager/elastic_request_generator.py"

engines:
  duplication:
    exclude_paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.scss"
      - ".nyc_output/**"
      - "coverage/**"
      - "backend/static/**"
      - "backend/migrations/**"
      - "backend/orion/services/elastic_manager/elastic_request_generator.py"
