engines:
  eslint:
    enabled: true
  bandit:
    enabled: true
  pylint:
    enabled: true
  stylelint:
    enabled: true

exclude_paths:
  - client/node_modules/
  - client/dist/
  - client/coverage/
  - client/tests/
  - backend/venv/
