exclude_paths:
  - client/cypress/**
  - backend/static/**
  - backend/orion/services/elastic_manager/elastic_request_generator.py
  - backend/migrations/**

engines:
  duplication:
    exclude_paths:
      - client/cypress/**
      - backend/static/**
      - backend/orion/services/elastic_manager/elastic_request_generator.py
      - backend/migrations/**
