exclude_paths:
  - "client/build/**"
  - "client/coverage/**"
  - "client/.angular/**"
  - "client/node_modules/**"
  - "client/.nyc_output/**"
  - "client/src/assets/**"
  - "client/*.config.*"
  - "**/*.html"
  - "**/*.css"
  - "**/*.scss"
  - "**/*.md"
  - "**/*.sh"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.map"
  - "**/__init__.py"
  - "**/eslint.config.js"
  - ".nyc_output/**"
  - "coverage/**"
  - "backend/tests/**"
  - "backend/static/**"
  - "backend/migrations/**"
  - "backend/orion/services/elastic_manager/elastic_request_generator.py"
  - client/cypress/**
  - backend/static/**
  - backend/migrations/**
  - backend/orion/services/elastic_manager/elastic_request_generator.py

engines:
  duplication:
    exclude_paths:
      - "client/build/**"
      - "client/coverage/**"
      - "client/.angular/**"
      - "client/node_modules/**"
      - "client/.nyc_output/**"
      - "client/src/assets/**"
      - "client/*.config.*"
      - "**/*.html"
      - "**/*.css"
      - "**/*.scss"
      - "**/__init__.py"
      - "**/eslint.config.js"
      - ".nyc_output/**"
      - "coverage/**"
      - "backend/tests/**"
      - "backend/static/**"
      - "backend/migrations/**"
      - "backend/orion/services/elastic_manager/elastic_request_generator.py"
      - client/cypress/**
      - backend/static/**
      - backend/migrations/**
      - backend/orion/services/elastic_manager/elastic_request_generator.py
