[main]
datadir = /var/lib/tor2web
transport = HTTP
listen_ipv4 = 0.0.0.0
listen_ipv6 = none
listen_port_http = 38080
basehost = AUTO
ssl_key = /var/lib/tor2web/certs/tor2web-key.pem
ssl_cert = /var/lib/tor2web/certs/tor2web-cert.pem
ssl_intermediate = /var/lib/tor2web/certs/tor2web-intermediate.pem
sockshost = tor
socksport = 9050
sockmaxpersistentperhost = 5
sockcachedconnectiontimeout = 240
sockretryautomatically = True
logreqs = True
debugmode = True
debugtostdout = True
processes = 1
requests_per_process = 100000
mode = BLOCKLIST
disable_gettor = True
disable_disclaimer = True
disable_banner = True
