worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    open_file_cache off;
    server_tokens off;
    server_names_hash_bucket_size 128;
    autoindex off;

    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=static_cache:10m max_size=1g inactive=60m use_temp_path=off;

    brotli on;
    brotli_comp_level 8;
    brotli_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        text/xml
        application/xml
        image/svg+xml
        application/x-javascript
        text/x-js;
    brotli_min_length 20;

    gzip on;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        text/xml
        application/xml
        image/svg+xml
        application/x-javascript
        text/x-js;
    gzip_min_length 20;
    gzip_vary on;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header Server "Secure Gateway" always;

server {
    listen 80;
    server_name try.orionintelligence.org;

    location /.well-known/acme-challenge/ {
        alias /var/www/letsencrypt/;
        try_files $uri =404;
    }

    location / {
        return 200 "Temporary HTTP enabled for Let's Encrypt validation.\n";
        add_header Content-Type text/plain;
    }
}

    server {
        listen 80;
        server_name zucui4cyyun2uok6x7mj3zyzgobcctcgugah33vrttbb7bxgj5quvjqd.onion;

        location / {
            proxy_pass http://trusted-web-main:8070;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto http;
            proxy_hide_header X-Powered-By;
            proxy_hide_header Server;
            proxy_hide_header X-AspNet-Version;
        }
    }
}
