// noinspection JSUnusedGlobalSymbols

export const LANGUAGE_MAP: Record<string, { iso1: string, name: string }> = {
  eng: { iso1: 'en', name: 'English' },
  fra: { iso1: 'fr', name: 'French' },
  spa: { iso1: 'es', name: 'Spanish' },
  deu: { iso1: 'de', name: 'German' },
  ita: { iso1: 'it', name: 'Italian' },
  por: { iso1: 'pt', name: 'Portuguese' },
  rus: { iso1: 'ru', name: 'Russian' },
  zho: { iso1: 'zh', name: 'Chinese' },
  jpn: { iso1: 'ja', name: 'Japanese' },
  kor: { iso1: 'ko', name: 'Korean' },
  ara: { iso1: 'ar', name: 'Arabic' },
  hin: { iso1: 'hi', name: 'Hindi' },
  ben: { iso1: 'bn', name: 'Bengali' },
  tur: { iso1: 'tr', name: 'Turkish' },
  nld: { iso1: 'nl', name: 'Dutch' },
  swe: { iso1: 'sv', name: 'Swedish' },
  pol: { iso1: 'pl', name: 'Polish' },
  ces: { iso1: 'cs', name: 'Czech' }
};

export const ChannelTypeKeys = [
  'BREACH',
  'CVE',
  'ZERODAY',
  'TOOLS',
  'WARFARE',
  'EMAIL',
  'LOGS',
  'CLOUD',
  'NEWS'
];

export enum SortType {
  DEFAULT = 'Default',
  NEWEST_FIRST = 'Newest first',
  OLDEST_FIRST = 'Oldest first'
}

export enum GraphType {
  Cluster = 'cluster',
  Document = 'document',
  Property = 'property'
}

export enum GraphClusterType {
  All = 'all',
  General = 'general',
  Leak = 'leak',
  Defacement = 'defacement',
  Chat = 'chat',
  Exploit = 'exploit'
}

export enum GraphAllowedPropertyKey {
  All = 'all',
  Email = 'm_email',
  TelephoneNumber = 'm_phone_number',
  URL = 'm_url',
  Litecoin = 'm_ltc',
  BitcoinCash = 'm_bch',
  Ethereum = 'm_eth',
  Bitcoin = 'm_btc',
  XmppAddresses = 'm_xmpp_addresses',
  GoogleAnalyticsIds = 'm_google_analytics_ids',
  Md5Hashes = 'm_md5_hashes',
  Sha1Hashes = 'm_sha1_hashes',
  Sha256Hashes = 'm_sha256_hashes',
  Hashes = 'm_hashes',
  Md5s = 'm_md5s',
  EnterpriseAttackTechniques = 'm_enterprise_attack_techniques',
  MacAddresses = 'm_mac_addresses',
  Domain = 'm_domain',
  CVE = 'm_cve',
  IPAddress = 'm_ip',
  YARARule = 'm_yara_rule',
  AWSSecret = 'm_aws_secret',
  FilePath = 'm_file_path',
  CreditCard = 'm_credit_card',
  Organization = 'm_org',
  GeopoliticalEntity = 'm_gpe',
  NORP = 'm_norp',
  Product = 'm_product',
  Person = 'm_person',
  Location = 'm_location',
  Law = 'm_law',
  INAadhaar = 'm_in_aadhaar',
  AUABN = 'm_au_abn',
  AUTFN = 'm_au_tfn',
  INVehicleRegistration = 'm_in_vehicle_registration',
  INPAN = 'm_in_pan',
  INVoter = 'm_in_voter',
  INPassport = 'm_in_passport',
  USITIN = 'm_us_itin',
  USSSN = 'm_us_ssn',
  USPassport = 'm_us_passport',
  USDriverLicense = 'm_us_driver_license',
  USBankNumber = 'm_us_bank_number',
  Username = 'm_username',
  Password = 'm_password',
  Hashtag = 'm_hashtag',
  Mention = 'm_mention',
  MITRETTPType = 'm_mitre_ttp_type',
  DocumentID = 'm_document_id',
  MedicalLicense = 'm_medical_license',
  CompanyName = 'm_company_name',
  EmployeeCount = 'm_employee_count',
  Team = 'm_team',
  Country = 'm_country',
  States = 'm_states',
  Language = 'm_language',
  EncodedURLs = 'm_encoded_urls',
  Dumplink = 'm_dumplink',
  UserAgents = 'm_user_agents',
  ASN = 'm_asns',
  Attacker = 'm_attacker',
  MITRETTPName = 'm_mitre_ttp_name',
  CWEs = 'm_cwe'
}

export const sidebarItemTooltips: Record<string, string> = {
  'All': 'Comprehensive Overview',
  'General': 'Broad Data Pool',
  'Forums': 'Forum Intelligence',
  'News': 'Trending Alerts',
  'Stolen': 'Stolen Info Logs',
  'Drugs': 'Narcotics Tracker',
  'Hacking': 'Hacking Insights',
  'Phishing': 'Phishing Records',
  'Marketplaces': 'Trade Monitoring',
  'Cryptocurrency': 'Crypto Transactions',
  'Leaks': 'Data Leaks',
  'Hacked': 'Hack Records',
  'Databases': 'Breach Records',
  'Tracking': 'Breach Tracker',
  'CVE': 'CVE',
  'Mitre': 'Mitre',
  'Listing': 'Listing',
  'Credential': 'Credential',
  'Email': 'Email',
  'Telegram': 'telegram',
  'Archive': 'archive',
  'Logs': 'Logs',
  'Warfare': 'Warfare',
  'Cloud': 'Cloud',
  'Tools': 'Tools',
  'ZeroDay': 'Zero Day',
};

export const dashboardTooltips: Record<string, string> = {
  'Top Teams (Leak)': 'Displays the teams most frequently involved in leak incidents.',
  'Top Teams (Defacement)': 'Highlights teams most affected by website defacements.',
  'Top Locations (Defacement)': 'Shows geographic regions with the highest number of defacement incidents.',
  'Top Hashtags (Social)': 'Lists the most used hashtags related to social media activity or incidents.',
};

export const FIELDS_MAP = {
  phoneNumbers: ['m_phone_number'],
  domains: ['m_domain'],
  cveCwe: ['m_cve', 'm_cwe'],
  litecoin: ['m_ltc'],
  bitcoinCash: ['m_bch'],
  ethereum: ['m_eth'],
  bitcoin: ['m_btc'],
  xmppAddresses: ['m_xmpp_addresses'],
  googleAnalyticsIds: ['m_google_analytics_ids'],
  md5Hashes: ['m_md5_hashes'],
  sha1Hashes: ['m_sha1_hashes'],
  sha256Hashes: ['m_sha256_hashes'],
  userAgents: ['m_user_agents'],
  hashes: ['m_hashes'],
  md5s: ['m_md5s'],
  enterpriseAttackTechniques: ['m_enterprise_attack_techniques'],
  macAddresses: ['m_mac_addresses'],
  ipAddresses: ['m_ip'],
  yaraRules: ['m_yara_rule'],
  awsSecrets: ['m_aws_secret'],
  filePaths: ['m_file_path'],
  creditCards: ['m_credit_card'],
  organizations: ['m_org', 'm_company_name'],
  geopoliticalEntities: ['m_gpe'],
  norps: ['m_norp'],
  products: ['m_product'],
  persons: ['m_person'],
  locations: ['m_location', 'm_country', 'm_states'],
  laws: ['m_law'],
  aadhaar: ['m_in_aadhaar'],
  australianIds: ['m_au_abn', 'm_au_tfn'],
  indianIds: ['m_in_vehicle_registration', 'm_in_pan', 'm_in_voter', 'm_in_passport'],
  usIds: ['m_us_itin', 'm_us_ssn', 'm_us_passport', 'm_us_driver_license'],
  usBankDetails: ['m_us_bank_number'],
  usernames: ['m_username'],
  passwords: ['m_password'],
  hashtags: ['m_hashtag'],
  mentions: ['m_mention'],
  mitreTtp: ['m_mitre_ttp_type', 'm_mitre_ttp_name'],
  documentIds: ['m_document_id'],
  medicalLicenses: ['m_medical_license'],
  employeeData: ['m_employee_count'],
  teams: ['m_team', 'm_attacker'],
  language: ['m_language'],
  asns: ['m_asns'],
  channels: ['m_channel_name'],
  senders: ['m_sender_name'],
  contentTypes: ['m_content_type', 'mContentType']
};

export const DATA_SECTION_TEMPLATE = [
  { title: 'Phone Numbers', key: 'isPhoneExpanded', fieldKey: 'phoneNumbers' },
  { title: 'Domains', key: 'isDomainExpanded', fieldKey: 'domains' },
  { title: 'CVE & CWE', key: 'isCveCweExpanded', fieldKey: 'cveCwe' },
  { title: 'IP Addresses', key: 'isIpExpanded', fieldKey: 'ipAddresses' },
  { title: 'YARA Rules', key: 'isYaraExpanded', fieldKey: 'yaraRules' },
  { title: 'AWS Secrets', key: 'isAwsExpanded', fieldKey: 'awsSecrets' },
  { title: 'File Paths', key: 'isFilePathExpanded', fieldKey: 'filePaths' },
  { title: 'Credit Cards', key: 'isCreditCardExpanded', fieldKey: 'creditCards' },
  { title: 'Organizations', key: 'isOrganizationExpanded', fieldKey: 'organizations' },
  { title: 'Geopolitical Entities', key: 'isGpeExpanded', fieldKey: 'geopoliticalEntities' },
  { title: 'NORPs', key: 'isNorpExpanded', fieldKey: 'norps' },
  { title: 'Products', key: 'isProductExpanded', fieldKey: 'products' },
  { title: 'Persons', key: 'isPersonExpanded', fieldKey: 'persons' },
  { title: 'Locations', key: 'isLocationExpanded', fieldKey: 'locations' },
  { title: 'Laws', key: 'isLawExpanded', fieldKey: 'laws' },
  { title: 'Aadhaar (IN)', key: 'isAadhaarExpanded', fieldKey: 'aadhaar' },
  { title: 'Australian IDs', key: 'isAustralianIdExpanded', fieldKey: 'australianIds' },
  { title: 'Indian IDs', key: 'isIndianIdExpanded', fieldKey: 'indianIds' },
  { title: 'US IDs', key: 'isUsIdExpanded', fieldKey: 'usIds' },
  { title: 'US Bank Numbers', key: 'isUsBankExpanded', fieldKey: 'usBankDetails' },
  { title: 'Usernames', key: 'isUsernameExpanded', fieldKey: 'usernames' },
  { title: 'Passwords', key: 'isPasswordExpanded', fieldKey: 'passwords' },
  { title: 'Hashtags', key: 'isHashtagExpanded', fieldKey: 'hashtags' },
  { title: 'Mentions', key: 'isMentionExpanded', fieldKey: 'mentions' },
  { title: 'MITRE TTP', key: 'isMitreExpanded', fieldKey: 'mitreTtp' },
  { title: 'Document IDs', key: 'isDocumentIdExpanded', fieldKey: 'documentIds' },
  { title: 'Medical Licenses', key: 'isMedicalExpanded', fieldKey: 'medicalLicenses' },
  { title: 'Employee Data', key: 'isEmployeeExpanded', fieldKey: 'employeeData' },
  { title: 'Teams', key: 'isTeamExpanded', fieldKey: 'teams' },
  { title: 'Languages', key: 'isLanguageExpanded', fieldKey: 'language' },
  { title: 'User Agents', key: 'isUserAgentExpanded', fieldKey: 'userAgents' },
  { title: 'ASNs', key: 'isAsnExpanded', fieldKey: 'asns' },
  { title: 'Channels', key: 'isChannelExpanded', fieldKey: 'channels' },
  { title: 'Senders', key: 'isSenderExpanded', fieldKey: 'senders' },
  { title: 'Content Types', key: 'isContentTypeExpanded', fieldKey: 'contentTypes' }
];

export const ALLOWED_CONSOLIDATED_RANKED_SINGLETON: Set<string> = new Set([
  "tools",
  "zeroday"
]);

export const search_filter_keys = new Set([
    'm_ltc', 'm_bch', 'm_eth', 'm_btc', 'm_xmpp_addresses', 'm_google_analytics_ids', 'm_md5_hashes', 'm_sha1_hashes', 'm_sha256_hashes', 'm_user_agents', 'm_hashes', 'm_md5s', 'm_enterprise_attack_techniques', 'm_mac_addresses',
    'm_search_all', 'm_asns', 'm_attacker', 'm_au_abn', 'm_au_acn', 'm_au_medicare', 'm_au_tfn', 'm_aws_secret', 'hashtags',
    'm_company_name', 'm_country', 'm_country_name', 'm_platform', 'm_credit_card', 'm_cve',
    'm_cwe', 'm_document_id', 'm_dumplink', 'm_email', 'm_employee_count',
    'm_encoded_urls', 'm_event', 'm_fac', 'm_file_path', 'm_file_paths', 'm_gpe', 'm_hashtag', 'm_author',
    'm_in_aadhaar', 'm_in_pan', 'm_in_passport', 'm_in_vehicle_registration', 'm_in_voter',
    'm_industry', 'm_ip', 'm_language', 'm_law', 'm_location', 'm_medical_license', 'm_mention',
    'm_mitre_ttp_name', 'm_mitre_ttp_type', 'm_monero_addresses', 'm_name', 'm_norp', 'm_org',
    'm_password', 'm_person', 'm_phone_number', 'm_product', 'm_social_media_profiles', 'm_states',
    'm_team', 'm_title', 'm_uk_nhs', 'm_uk_nino', 'm_url', 'm_us_bank_number', 'm_us_driver_license',
    'm_us_itin', 'm_us_passport', 'm_us_ssn', 'm_user_agents', 'm_username', 'm_xmpp_addresses',
    'm_yara_rule', 'm_domain'
]);
export const search_filter_labels: { [key: string]: string } = {
  m_search_all: 'Search All',
  m_asns: 'ASNs',
  m_attacker: 'Attacker',
  m_au_abn: 'AU ABN',
  m_au_acn: 'AU ACN',
  m_au_medicare: 'AU Medicare',
  m_au_tfn: 'AU TFN',
  m_aws_secret: 'AWS Secret',
  hashtags: 'Hashtags',
  m_bitcoin_addresses: 'Bitcoin Addresses',
  m_company_name: 'Company Name',
  m_country: 'Country',
  m_platform: 'Platform',
  m_credit_card: 'Credit Card',
  m_cve: 'CVE',
  m_ltc: 'Litecoin',
  m_bch: 'Bitcoin Cash',
  m_eth: 'Ethereum',
  m_btc: 'Bitcoin',
  m_xmpp_addresses: 'XMPP Addresses',
  m_google_analytics_ids: 'Google Analytics IDs',
  m_md5_hashes: 'MD5 Hashes',
  m_sha1_hashes: 'SHA1 Hashes',
  m_sha256_hashes: 'SHA256 Hashes',
  m_user_agents: 'User Agents',
  m_hashes: 'Hashes',
  m_md5s: 'MD5s',
  m_enterprise_attack_techniques: 'Enterprise ATT&CK Techniques',
  m_mac_addresses: 'MAC Addresses',
  m_cwe: 'CWE',
  m_document_id: 'Document ID',
  m_dumplink: 'Dump Link',
  m_email: 'Email',
  m_employee_count: 'Employee Count',
  m_encoded_urls: 'Encoded URLs',
  m_event: 'Event',
  m_fac: 'FAC',
  m_file_path: 'File Path',
  m_file_paths: 'File Paths',
  m_gpe: 'GPE',
  m_hashtag: 'Hashtag',
  m_author: 'Author',
  m_in_aadhaar: 'IN Aadhaar',
  m_in_pan: 'IN PAN',
  m_in_passport: 'IN Passport',
  m_in_vehicle_registration: 'IN Vehicle Registration',
  m_in_voter: 'IN Voter',
  m_industry: 'Industry',
  m_ip: 'IP Address',
  m_language: 'Language',
  m_law: 'Law',
  m_location: 'Location',
  m_medical_license: 'Medical License',
  m_mention: 'Mention',
  m_mitre_ttp_name: 'MITRE TTP Name',
  m_mitre_ttp_type: 'MITRE TTP Type',
  m_monero_addresses: 'Monero Addresses',
  m_name: 'Name',
  m_norp: 'NORP',
  m_org: 'Organization',
  m_password: 'Password',
  m_person: 'Person',
  m_phone_number: 'Phone Number',
  m_product: 'Product',
  m_social_media_profiles: 'Social Media Profiles',
  m_states: 'States',
  m_team: 'Team',
  m_title: 'Title',
  m_uk_nhs: 'UK NHS',
  m_uk_nino: 'UK NINO',
  m_url: 'URL',
  m_us_bank_number: 'US Bank Number',
  m_us_driver_license: 'US Driver License',
  m_us_itin: 'US ITIN',
  m_us_passport: 'US Passport',
  m_us_ssn: 'US SSN',
  m_username: 'Username',
  m_yara_rule: 'YARA Rule',
  m_domain: 'Domain',
};
