export const LANGUAGE_MAP: Record<string, { iso1: string, name: string }> = {
  eng: {iso1: 'en', name: 'English'},
  fra: {iso1: 'fr', name: 'French'},
  spa: {iso1: 'es', name: 'Spanish'},
  deu: {iso1: 'de', name: 'German'},
  ita: {iso1: 'it', name: 'Italian'},
  por: {iso1: 'pt', name: 'Portuguese'},
  rus: {iso1: 'ru', name: 'Russian'},
  zho: {iso1: 'zh', name: 'Chinese'},
  jpn: {iso1: 'ja', name: 'Japanese'},
  kor: {iso1: 'ko', name: 'Korean'},
  ara: {iso1: 'ar', name: 'Arabic'},
  hin: {iso1: 'hi', name: 'Hindi'},
  ben: {iso1: 'bn', name: 'Bengali'},
  tur: {iso1: 'tr', name: 'Turkish'},
  nld: {iso1: 'nl', name: 'Dutch'},
  swe: {iso1: 'sv', name: 'Swedish'},
  pol: {iso1: 'pl', name: 'Polish'},
  ces: {iso1: 'cs', name: 'Czech'}
};

export const DUMP_SOURCE_MAP: Record<number, { name: string }> = {
  1: {name: 'Telegram'},
};

export const DUMP_GROUP_MAP: Record<number, { name: string }> = {
  1: {name: 'Dataleak 2025'},
};

export const ChannelTypeKeys = [
  'BREACH',
  'CVE',
  'ZERODAY',
  'TOOLS',
  'WARFARE',
  'EMAIL',
  'LOGS',
  'CLOUD',
  'NEWS'
];

export enum SortType {
  DEFAULT = 'Default',
  NEWEST_FIRST = 'Newest first',
  OLDEST_FIRST = 'Oldest first'
}

export enum GraphType {
  Cluster = 'cluster',
  Document = 'document',
  Property = 'property'
}

export enum GraphClusterType {
  All = 'all',
  General = 'general',
  Leak = 'leak',
  Defacement = 'defacement',
  Chat = 'chat',
  Exploit = 'exploit'
}

export enum GraphAllowedPropertyKey {
  All = 'all',
  Email = 'm_email',
  BitcoinAddresses = 'm_bitcoin_addresses',
  TelephoneNumber = 'm_phone_number',
  URL = 'm_url',
  Domain = 'm_domain',
  CVE = 'm_cve',
  IPAddress = 'm_ip',
  YARARule = 'm_yara_rule',
  AWSSecret = 'm_aws_secret',
  FilePath = 'm_file_path',
  CreditCard = 'm_credit_card',
  Organization = 'm_org',
  GeopoliticalEntity = 'm_gpe',
  NORP = 'm_norp',
  Product = 'm_product',
  Person = 'm_person',
  Location = 'm_location',
  Law = 'm_law',
  INAadhaar = 'm_in_aadhaar',
  AUABN = 'm_au_abn',
  AUTFN = 'm_au_tfn',
  INVehicleRegistration = 'm_in_vehicle_registration',
  INPAN = 'm_in_pan',
  INVoter = 'm_in_voter',
  INPassport = 'm_in_passport',
  USITIN = 'm_us_itin',
  USSSN = 'm_us_ssn',
  USPassport = 'm_us_passport',
  USDriverLicense = 'm_us_driver_license',
  USBankNumber = 'm_us_bank_number',
  Username = 'm_username',
  Password = 'm_password',
  Hashtag = 'm_hashtag',
  Mention = 'm_mention',
  MITRETTPType = 'm_mitre_ttp_type',
  DocumentID = 'm_document_id',
  MedicalLicense = 'm_medical_license',
  CompanyName = 'm_company_name',
  EmployeeCount = 'm_employee_count',
  Team = 'm_team',
  Country = 'm_country',
  States = 'm_states',
  Language = 'm_language',
  EncodedURLs = 'm_encoded_urls',
  Dumplink = 'm_dumplink',
  UserAgents = 'm_user_agents',
  ASN = 'm_asns',
  Attacker = 'm_attacker',
  MITRETTPName = 'm_mitre_ttp_name',
  CWEs = 'm_cwe'
}

export const sidebarItemTooltips: Record<string, string> = {
  'All': 'Comprehensive Overview',
  'General': 'Broad Data Pool',
  'Forums': 'Forum Intelligence',
  'News': 'Trending Alerts',
  'Stolen': 'Stolen Info Logs',
  'Drugs': 'Narcotics Tracker',
  'Hacking': 'Hacking Insights',
  'Phishing': 'Phishing Records',
  'Marketplaces': 'Trade Monitoring',
  'Cryptocurrency': 'Crypto Transactions',
  'Leaks': 'Data Leaks',
  'Hacked': 'Hack Records',
  'Databases': 'Breach Records',
  'Tracking': 'Breach Tracker',
  'CVE': 'CVE',
  'Mitre': 'Mitre',
  'Listing': 'Listing',
  'Credential': 'Credential',
  'Email': 'Email',
  'Telegram': 'telegram',
  'Archive': 'archive',
  'Logs': 'Logs',
  'Warfare': 'Warfare',
  'Cloud': 'Cloud',
  'Tools': 'Tools',
  'ZeroDay': 'Zero Day',
};

export const dashboardTooltips: Record<string, string> = {
  'Top Teams (Leak)': 'Displays the teams most frequently involved in leak incidents.',
  'Top Teams (Defacement)': 'Highlights teams most affected by website defacements.',
  'Top Locations (Defacement)': 'Shows geographic regions with the highest number of defacement incidents.',
  'Top Hashtags (Social)': 'Lists the most used hashtags related to social media activity or incidents.',
};

export const fieldsMap = {
  bitcoinAddresses: ['m_bitcoin_addresses'],
  phoneNumbers: ['m_phone_number'],
  domains: ['m_domain'],
  cveCwe: ['m_cve', 'm_cwe'],
  ipAddresses: ['m_ip'],
  yaraRules: ['m_yara_rule'],
  awsSecrets: ['m_aws_secret'],
  filePaths: ['m_file_path'],
  creditCards: ['m_credit_card'],
  organizations: ['m_org', 'm_company_name'],
  geopoliticalEntities: ['m_gpe'],
  norps: ['m_norp'],
  products: ['m_product'],
  persons: ['m_person'],
  locations: ['m_location', 'm_country', 'm_states'],
  laws: ['m_law'],
  aadhaar: ['m_in_aadhaar'],
  australianIds: ['m_au_abn', 'm_au_tfn'],
  indianIds: ['m_in_vehicle_registration', 'm_in_pan', 'm_in_voter', 'm_in_passport'],
  usIds: ['m_us_itin', 'm_us_ssn', 'm_us_passport', 'm_us_driver_license'],
  usBankDetails: ['m_us_bank_number'],
  usernames: ['m_username'],
  passwords: ['m_password'],
  hashtags: ['m_hashtag'],
  mentions: ['m_mention'],
  mitreTtp: ['m_mitre_ttp_type', 'm_mitre_ttp_name'],
  documentIds: ['m_document_id'],
  medicalLicenses: ['m_medical_license'],
  employeeData: ['m_employee_count'],
  teams: ['m_team', 'm_attacker'],
  language: ['m_language'],
  userAgents: ['m_user_agents'],
  asns: ['m_asns'],
  channels: ['m_channel_name'],
  senders: ['m_sender_name'],
  contentTypes: ['m_content_type', 'mContentType']
};

export const FIELDS_MAP = {
  bitcoinAddresses: ['m_bitcoin_addresses'],
  phoneNumbers: ['m_phone_number'],
  domains: ['m_domain'],
  cveCwe: ['m_cve', 'm_cwe'],
  ipAddresses: ['m_ip'],
  yaraRules: ['m_yara_rule'],
  awsSecrets: ['m_aws_secret'],
  filePaths: ['m_file_path'],
  creditCards: ['m_credit_card'],
  organizations: ['m_org', 'm_company_name'],
  geopoliticalEntities: ['m_gpe'],
  norps: ['m_norp'],
  products: ['m_product'],
  persons: ['m_person'],
  locations: ['m_location', 'm_country', 'm_states'],
  laws: ['m_law'],
  aadhaar: ['m_in_aadhaar'],
  australianIds: ['m_au_abn', 'm_au_tfn'],
  indianIds: ['m_in_vehicle_registration', 'm_in_pan', 'm_in_voter', 'm_in_passport'],
  usIds: ['m_us_itin', 'm_us_ssn', 'm_us_passport', 'm_us_driver_license'],
  usBankDetails: ['m_us_bank_number'],
  usernames: ['m_username'],
  passwords: ['m_password'],
  hashtags: ['m_hashtag'],
  mentions: ['m_mention'],
  mitreTtp: ['m_mitre_ttp_type', 'm_mitre_ttp_name'],
  documentIds: ['m_document_id'],
  medicalLicenses: ['m_medical_license'],
  employeeData: ['m_employee_count'],
  teams: ['m_team', 'm_attacker'],
  language: ['m_language'],
  userAgents: ['m_user_agents'],
  asns: ['m_asns'],
  channels: ['m_channel_name'],
  senders: ['m_sender_name'],
  contentTypes: ['m_content_type', 'mContentType']
};

export const DATA_SECTION_TEMPLATE = [
  { title: 'Bitcoin Addresses', key: 'isBitcoinExpanded', fieldKey: 'bitcoinAddresses' },
  { title: 'Phone Numbers', key: 'isPhoneExpanded', fieldKey: 'phoneNumbers' },
  { title: 'Domains', key: 'isDomainExpanded', fieldKey: 'domains' },
  { title: 'CVE & CWE', key: 'isCveCweExpanded', fieldKey: 'cveCwe' },
  { title: 'IP Addresses', key: 'isIpExpanded', fieldKey: 'ipAddresses' },
  { title: 'YARA Rules', key: 'isYaraExpanded', fieldKey: 'yaraRules' },
  { title: 'AWS Secrets', key: 'isAwsExpanded', fieldKey: 'awsSecrets' },
  { title: 'File Paths', key: 'isFilePathExpanded', fieldKey: 'filePaths' },
  { title: 'Credit Cards', key: 'isCreditCardExpanded', fieldKey: 'creditCards' },
  { title: 'Organizations', key: 'isOrganizationExpanded', fieldKey: 'organizations' },
  { title: 'Geopolitical Entities', key: 'isGpeExpanded', fieldKey: 'geopoliticalEntities' },
  { title: 'NORPs', key: 'isNorpExpanded', fieldKey: 'norps' },
  { title: 'Products', key: 'isProductExpanded', fieldKey: 'products' },
  { title: 'Persons', key: 'isPersonExpanded', fieldKey: 'persons' },
  { title: 'Locations', key: 'isLocationExpanded', fieldKey: 'locations' },
  { title: 'Laws', key: 'isLawExpanded', fieldKey: 'laws' },
  { title: 'Aadhaar (IN)', key: 'isAadhaarExpanded', fieldKey: 'aadhaar' },
  { title: 'Australian IDs', key: 'isAustralianIdExpanded', fieldKey: 'australianIds' },
  { title: 'Indian IDs', key: 'isIndianIdExpanded', fieldKey: 'indianIds' },
  { title: 'US IDs', key: 'isUsIdExpanded', fieldKey: 'usIds' },
  { title: 'US Bank Numbers', key: 'isUsBankExpanded', fieldKey: 'usBankDetails' },
  { title: 'Usernames', key: 'isUsernameExpanded', fieldKey: 'usernames' },
  { title: 'Passwords', key: 'isPasswordExpanded', fieldKey: 'passwords' },
  { title: 'Hashtags', key: 'isHashtagExpanded', fieldKey: 'hashtags' },
  { title: 'Mentions', key: 'isMentionExpanded', fieldKey: 'mentions' },
  { title: 'MITRE TTP', key: 'isMitreExpanded', fieldKey: 'mitreTtp' },
  { title: 'Document IDs', key: 'isDocumentIdExpanded', fieldKey: 'documentIds' },
  { title: 'Medical Licenses', key: 'isMedicalExpanded', fieldKey: 'medicalLicenses' },
  { title: 'Employee Data', key: 'isEmployeeExpanded', fieldKey: 'employeeData' },
  { title: 'Teams', key: 'isTeamExpanded', fieldKey: 'teams' },
  { title: 'Languages', key: 'isLanguageExpanded', fieldKey: 'language' },
  { title: 'User Agents', key: 'isUserAgentExpanded', fieldKey: 'userAgents' },
  { title: 'ASNs', key: 'isAsnExpanded', fieldKey: 'asns' },
  { title: 'Channels', key: 'isChannelExpanded', fieldKey: 'channels' },
  { title: 'Senders', key: 'isSenderExpanded', fieldKey: 'senders' },
  { title: 'Content Types', key: 'isContentTypeExpanded', fieldKey: 'contentTypes' }
];

export const ALLOWED_CONSOLIDATED_RANKED_SINGLETON: Set<string> = new Set([
  "tools",
  "zeroday"
]);
