ACTOR_CONTEXT_CLUSTERS = {"leak", "defacement", "apt", "malware"}

TARGET_CONTEXT_CLUSTERS = {"leak", "defacement", "exploit", "apt", "malware"}

SOURCE_ENTITY_KEYS = {"m_author", "m_reporter", "m_team"}

ORG_SUFFIXES = {
    "co",
    "company",
    "corp",
    "corporation",
    "gmbh",
    "inc",
    "incorporated",
    "llc",
    "ltd",
    "limited",
    "plc",
    "sa",
}

CLUSTER_RELIABILITY_BASE = {
    "apt": 0.78,
    "chat": 0.55,
    "defacement": 0.6,
    "exploit": 0.72,
    "general": 0.66,
    "leak": 0.64,
    "malware": 0.78,
    "news": 0.66,
    "social": 0.55,
    "tracking": 0.64,
}

DEFAULT_SOURCE_RELIABILITY = 0.62

CONFIDENCE_LABEL_SCORES = {
    "confirmed": 0.9,
    "critical": 0.9,
    "high": 0.82,
    "low": 0.45,
    "medium": 0.68,
    "unknown": DEFAULT_SOURCE_RELIABILITY,
}

HASH_KEY_BY_HEX_LENGTH = {
    32: "m_md5",
    40: "m_sha1",
    64: "m_sha256",
    96: "m_sha3_384",
}

DERIVED_USES_KEYS = {
    "m_asns",
    "m_currencies",
    "m_cve",
    "m_cwe",
    "m_crypto_address",
    "m_domain",
    "m_encoded_urls",
    "m_enterprise_attack_tactics",
    "m_enterprise_attack_techniques",
    "m_family",
    "m_file_name",
    "m_file_paths",
    "m_file_type",
    "m_imphash",
    "m_ip",
    "m_mac_address",
    "m_md5",
    "m_platform",
    "m_product",
    "m_registry_key_path",
    "m_sha1",
    "m_sha3_384",
    "m_sha256",
    "m_signature",
    "m_telfhash",
    "m_tlsh",
    "m_url",
    "m_user_agents",
    "m_vendor",
    "m_version",
    "m_vulnerability",
    "m_web_server",
    "m_yara_rule",
}

REPORT_METADATA_KEYS = {
    "m_base_url",
    "m_channel_name",
    "m_channel_url",
    "m_comment_count",
    "m_content_type",
    "m_creation_date",
    "m_date",
    "m_document_id",
    "m_edit_date",
    "m_external_scanners",
    "m_file_attributes",
    "m_forwarded_date",
    "m_group_name",
    "m_hash",
    "m_highlighted",
    "m_important_content",
    "m_is_forwarded",
    "m_is_reply",
    "m_leak_date",
    "m_likes",
    "m_message_id",
    "m_message_sharable_link",
    "m_mime_type",
    "m_name",
    "m_network",
    "m_pinned",
    "m_platform",
    "m_post_comments_count",
    "m_retweets",
    "m_scrap_file",
    "m_sender_id",
    "m_sender_is_bot",
    "m_source_channel_url",
    "m_source_url",
    "m_title",
    "m_update_date",
    "m_url",
}

REPORT_TITLE_KEYS = ("m_title", "m_name", "m_channel_name", "m_url", "m_base_url", "m_message_sharable_link")

REPORT_SUMMARY_KEYS = ("m_important_content", "m_content", "m_caption", "m_media_caption", "m_meta_description")

REPORT_DATE_KEYS = (
    "m_date",
    "m_leak_date",
    "m_published_date",
    "m_last_updated",
    "m_creation_date",
    "m_update_date",
    "m_first_seen",
    "m_edit_date",
)

SKIP_GRAPH_ENTITY_KEYS = {"m_document_id", "m_language", "m_scrap_file"}

SPLIT_VALUE_KEYS = {"m_country", "m_origin_country"}

GRAPH_EXTRA_KEY_TITLES = {
    "m_alias": "Alias",
    "m_asns": "ASN",
    "m_attacker": "Threat Actor",
    "m_author": "Author",
    "m_company_name": "Company",
    "m_country": "Country",
    "m_crypto_address": "Crypto Address",
    "m_currencies": "Currency",
    "m_cve": "CVE",
    "m_cvss": "CVSS",
    "m_cwe": "CWE",
    "m_domain": "Domain",
    "m_email": "Email",
    "m_encoded_urls": "Encoded URL",
    "m_enterprise_attack_tactics": "MITRE Tactic",
    "m_enterprise_attack_techniques": "MITRE Technique",
    "m_family": "Family",
    "m_file_name": "File Name",
    "m_file_paths": "File Path",
    "m_file_type": "File Type",
    "m_first_seen": "First Seen",
    "m_hashtag": "Hashtag",
    "m_hashes": "Hash",
    "m_imphash": "Imphash",
    "m_industry": "Industry",
    "m_ip": "IP Address",
    "m_last_seen": "Last Seen",
    "m_location": "Location",
    "m_mac_address": "MAC Address",
    "m_md5": "MD5",
    "m_mention": "Mention",
    "m_network": "Network",
    "m_org": "Organization",
    "m_origin_country": "Origin Country",
    "m_person": "Person",
    "m_phone_number": "Phone Number",
    "m_platform": "Platform",
    "m_product": "Product",
    "m_remote_type": "Remote Type",
    "m_reporter": "Reporter",
    "m_registry_key_path": "Registry Key Path",
    "m_risk": "Risk",
    "m_severity": "Severity",
    "m_sha1": "SHA1",
    "m_sha3_384": "SHA3-384",
    "m_sha256": "SHA256",
    "m_signature": "Signature",
    "m_social_media_profiles": "Social Profile",
    "m_tags": "Tag",
    "m_team": "Team",
    "m_telfhash": "Telfhash",
    "m_tlsh": "TLSH",
    "m_url": "URL",
    "m_uk_nhs": "UK NHS Number",
    "m_username": "Username",
    "m_us_driver_license": "US Driver License",
    "m_user_agents": "User Agent",
    "m_vendor": "Vendor",
    "m_version": "Version",
    "m_vulnerability": "Vulnerability",
    "m_web_server": "Web Server",
    "m_xmpp_addresses": "XMPP Address",
    "m_yara_rule": "YARA Rule",
}

ENTITY_CLASS_BY_KEY = {
    "m_alias": "alias",
    "m_asns": "infrastructure",
    "m_attacker": "threat_actor",
    "m_author": "source",
    "m_company_name": "organization",
    "m_country": "geo",
    "m_crypto_address": "financial_indicator",
    "m_currencies": "financial_indicator",
    "m_cve": "vulnerability",
    "m_cvss": "risk",
    "m_cwe": "weakness",
    "m_domain": "infrastructure",
    "m_email": "identity",
    "m_encoded_urls": "infrastructure",
    "m_enterprise_attack_tactics": "attack_pattern",
    "m_enterprise_attack_techniques": "attack_pattern",
    "m_family": "threat_family",
    "m_file_name": "file",
    "m_file_paths": "file",
    "m_file_type": "file",
    "m_first_seen": "time",
    "m_hashtag": "social_marker",
    "m_imphash": "file_hash",
    "m_industry": "sector",
    "m_ip": "infrastructure",
    "m_last_seen": "time",
    "m_location": "geo",
    "m_mac_address": "infrastructure",
    "m_md5": "file_hash",
    "m_mention": "social_marker",
    "m_network": "network",
    "m_org": "organization",
    "m_origin_country": "geo",
    "m_person": "identity",
    "m_phone_number": "identity",
    "m_platform": "platform",
    "m_product": "product",
    "m_remote_type": "exploit_context",
    "m_reporter": "source",
    "m_registry_key_path": "host_indicator",
    "m_risk": "risk",
    "m_severity": "risk",
    "m_sha1": "file_hash",
    "m_sha3_384": "file_hash",
    "m_sha256": "file_hash",
    "m_signature": "signature",
    "m_social_media_profiles": "identity",
    "m_tags": "tag",
    "m_team": "source",
    "m_telfhash": "file_hash",
    "m_tlsh": "file_hash",
    "m_url": "infrastructure",
    "m_uk_nhs": "identity_document",
    "m_username": "identity",
    "m_us_driver_license": "identity_document",
    "m_user_agents": "infrastructure",
    "m_vendor": "organization",
    "m_version": "product",
    "m_vulnerability": "vulnerability",
    "m_web_server": "platform",
    "m_xmpp_addresses": "identity",
    "m_yara_rule": "detection",
}

EDGE_TYPE_BY_KEY = {
    "m_alias": "has_alias",
    "m_asns": "reports_indicator",
    "m_attacker": "attributed_to_actor",
    "m_author": "published_by_source",
    "m_company_name": "targets_organization",
    "m_country": "mentions_geo",
    "m_crypto_address": "reports_financial_indicator",
    "m_currencies": "reports_financial_indicator",
    "m_cve": "reports_vulnerability",
    "m_cvss": "reports_risk",
    "m_cwe": "reports_weakness",
    "m_domain": "reports_indicator",
    "m_email": "reports_identity",
    "m_encoded_urls": "reports_indicator",
    "m_enterprise_attack_tactics": "maps_to_tactic",
    "m_enterprise_attack_techniques": "maps_to_technique",
    "m_family": "reports_threat_family",
    "m_file_name": "reports_file",
    "m_file_paths": "reports_file",
    "m_file_type": "reports_file",
    "m_first_seen": "observed_time",
    "m_hashtag": "mentions_marker",
    "m_imphash": "reports_file_hash",
    "m_industry": "targets_sector",
    "m_ip": "reports_indicator",
    "m_last_seen": "observed_time",
    "m_location": "mentions_geo",
    "m_mac_address": "reports_indicator",
    "m_mention": "mentions_marker",
    "m_network": "observed_on_network",
    "m_org": "targets_organization",
    "m_origin_country": "mentions_geo",
    "m_person": "mentions_identity",
    "m_phone_number": "reports_identity",
    "m_platform": "affects_platform",
    "m_product": "affects_product",
    "m_reporter": "published_by_source",
    "m_registry_key_path": "reports_host_indicator",
    "m_remote_type": "reports_exploit_context",
    "m_risk": "reports_risk",
    "m_severity": "reports_risk",
    "m_sha1": "reports_file_hash",
    "m_sha3_384": "reports_file_hash",
    "m_sha256": "reports_file_hash",
    "m_md5": "reports_file_hash",
    "m_signature": "reports_signature",
    "m_social_media_profiles": "reports_identity",
    "m_tags": "mentions_tag",
    "m_team": "published_by_source",
    "m_telfhash": "reports_file_hash",
    "m_tlsh": "reports_file_hash",
    "m_url": "reports_indicator",
    "m_uk_nhs": "reports_identity",
    "m_username": "reports_identity",
    "m_us_driver_license": "reports_identity",
    "m_user_agents": "reports_indicator",
    "m_vendor": "affects_vendor",
    "m_version": "affects_product",
    "m_vulnerability": "reports_vulnerability",
    "m_web_server": "affects_platform",
    "m_xmpp_addresses": "reports_identity",
    "m_yara_rule": "reports_detection",
}

DEFAULT_HIDDEN_KEYS = {"m_author", "m_country", "m_location", "m_reporter", "m_team"}
