name: Codacy Security Scan

on:
  push:
    branches:
      - trusted-main
      - devel
  pull_request:
    branches:
      - trusted-main

jobs:
  codacy-security-scan:
    runs-on: ubuntu-latest
    name: Codacy Security Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Codacy Security Scan
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: 39eddc129f0649bfbc706815ccd81eec
          verbose: true